background-opacity = 0.95
# background-blur = true
background-blur = macos-glass-regular
macos-titlebar-style = transparent

# Forward a few cmd keys to nvim as <D-…> (see nvim/lua/core/zed.lua)
keybind = super+j=csi:106;9u
keybind = super+b=csi:98;9u
keybind = super+s=csi:115;9u
keybind = super+/=csi:47;9u
