# ruff.toml

line-length = 100
unsafe-fixes = true

[lint]
fixable = ["ALL"]
select = [
    "E",   # Style errors
    "F",   # Python errors
    "I",   # Import sorting
    "B",   # Bugbear rules
    "UP",  # Python upgrade checks
    "C4",  # Comprehension checks
    "FA",  # Future annotations
    "SIM", # Simplification
    "PTH", # pathlib usage
    "TC",  # Type-checking import conventions
]
extend-select = [
    "ALL",
    # "PTH105",
    # "I",
]
ignore = [
    "T201", # print statement
    "RUF002", # ambiguous variable names
    "ERA001", # commented-out code
    "D100", # missing docstring in public module
]


[format]
quote-style = "double"
skip-magic-trailing-comma = false
